import {test, before, after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {Miniflare} from 'miniflare';
let mf;
const owner={'oai-authenticated-user-id':'verified-owner','oai-authenticated-user-email':'owner@example.test'};
const stranger={'oai-authenticated-user-id':'different-user','oai-authenticated-user-email':'stranger@example.test'};
async function call(path,{method='GET',data,headers={}}={}){return mf.dispatchFetch('https://portfolio.test'+path,{method,headers:{...(method!=='GET'?{Origin:'https://portfolio.test','Content-Type':'application/json'}:{}),...headers},body:data===undefined?undefined:JSON.stringify(data),redirect:'manual'});}
before(async()=>{mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',d1Databases:['DB'],r2Buckets:['MEDIA'],bindings:{ADMIN_OWNER_EMAIL:'owner@example.test'},assets:{directory:'dist/client',binding:'ASSETS',routerConfig:{has_user_worker:true}}});const db=await mf.getD1Database('DB');for(const name of (await fs.readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort()){for(const sql of (await fs.readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await db.prepare(sql).run();}});
after(async()=>{await mf?.dispose();});
test('anonymous visitors cannot reach admin data or claim ownership',async()=>{assert.equal((await call('/api/admin/projects')).status,401);assert.equal((await call('/admin')).status,302);assert.equal((await call('/admin/index.html')).status,404);assert.equal((await call('/api/admin/session',{headers:stranger})).status,403);assert.equal((await call('/api/content')).status,200);});
test('owner enrollment is stable and all admin mutations reject other identities and foreign origins',async()=>{assert.equal((await call('/api/admin/session',{headers:owner})).status,200);assert.equal((await call('/api/admin/session',{headers:{...stranger,'oai-authenticated-user-email':owner['oai-authenticated-user-email']}})).status,403);assert.equal((await call('/api/admin/projects',{method:'POST',data:{},headers:stranger})).status,403);assert.equal((await call('/api/admin/projects',{method:'POST',data:{},headers:{...owner,Origin:'https://evil.test'}})).status,403);});
test('drafts are private; publishing, hiding, order and optimistic conflicts persist',async()=>{const p={id:'test-result',category:'design',status:'draft',position:0,title:{en:'Result',ru:'Результат'},description:{en:'A result',ru:'Результат'},result:{en:'Finished result',ru:'Готовая работа'},cover:'/assets/images/project-04.jpg',gallery:[],video:'',link:'https://example.com/',tech:'Photoshop',concept:false};assert.equal((await call('/api/admin/projects',{method:'POST',data:p,headers:owner})).status,200);assert.ok(!(await (await call('/api/content')).json()).projects.some(x=>x.id===p.id));assert.equal((await call('/api/admin/projects/test-result')).status,401);let list=await (await call('/api/admin/projects',{headers:owner})).json();let saved=list.find(x=>x.id===p.id);assert.equal((await call('/api/admin/projects',{method:'POST',data:{...saved,status:'published'},headers:owner})).status,200);assert.ok((await (await call('/api/content')).json()).projects.some(x=>x.id===p.id));assert.equal((await call('/api/admin/projects',{method:'POST',data:saved,headers:owner})).status,409);assert.equal((await call('/api/admin/projects',{method:'POST',data:{...saved,revision:2,status:'hidden'},headers:owner})).status,200);assert.ok(!(await (await call('/api/content')).json()).projects.some(x=>x.id===p.id));});
test('uploaded images stay private until referenced by a published project',async()=>{const bytes=Uint8Array.from([137,80,78,71,13,10,26,10]);const response=await mf.dispatchFetch('https://portfolio.test/api/admin/upload',{method:'POST',headers:{...owner,Origin:'https://portfolio.test','Content-Type':'image/png'},body:bytes});assert.equal(response.status,201);const {url}=await response.json();assert.equal((await call(url)).status,404);assert.equal((await call(url,{headers:owner})).status,200);let p=(await (await call('/api/admin/projects',{headers:owner})).json()).find(x=>x.id==='test-result');assert.equal((await call('/api/admin/projects',{method:'POST',data:{...p,status:'published',cover:url},headers:owner})).status,200);assert.equal((await call(url)).status,200);p=(await (await call('/api/admin/projects',{headers:owner})).json()).find(x=>x.id==='test-result');await call('/api/admin/projects',{method:'POST',data:{...p,status:'hidden'},headers:owner});assert.equal((await call(url)).status,404);});
test('settings support both languages and protect concurrent changes',async()=>{const settings=await (await call('/api/admin/settings',{headers:owner})).json();const data={...settings,copy:{'WEB DEVELOPMENT':{en:'Websites',ru:'Сайты'}}};assert.equal((await call('/api/admin/settings',{method:'POST',data,headers:owner})).status,200);assert.equal((await call('/api/admin/settings',{method:'POST',data,headers:owner})).status,409);const content=await (await call('/api/content')).json();assert.equal(content.settings.copy['WEB DEVELOPMENT'].ru,'Сайты');});
test('inquiries are durable, owner-only and rate limited',async()=>{const data={service:'web',description:'A detailed project inquiry',contact:'client@example.test',website:''};assert.equal((await call('/api/inquiries',{method:'POST',data,headers:{Origin:'https://evil.test'}})).status,403);assert.equal((await call('/api/inquiries',{method:'POST',data})).status,201);assert.equal((await call('/api/admin/inquiries')).status,401);let rows=await (await call('/api/admin/inquiries',{headers:owner})).json();assert.equal(rows.length,1);assert.equal(rows[0].contact,'client@example.test');await call('/api/admin/inquiries',{method:'POST',data:{id:rows[0].id,status:'read'},headers:owner});rows=await (await call('/api/admin/inquiries',{headers:owner})).json();assert.equal(rows[0].status,'read');for(let i=0;i<4;i++)assert.equal((await call('/api/inquiries',{method:'POST',data})).status,201);assert.equal((await call('/api/inquiries',{method:'POST',data})).status,429);});
test('unsafe URLs and invalid uploads are rejected',async()=>{const p=(await (await call('/api/admin/projects',{headers:owner})).json())[0];assert.equal((await call('/api/admin/projects',{method:'POST',data:{...p,link:'javascript:alert(1)'},headers:owner})).status,400);const r=await mf.dispatchFetch('https://portfolio.test/api/admin/upload',{method:'POST',headers:{...owner,Origin:'https://portfolio.test','Content-Type':'image/svg+xml'},body:'<svg/>'});assert.equal(r.status,400);});
